### ISSUE TITLE
can we get a docker-compose.yml sample file?

### ISSUE THREAD

**Issue by ralyodio** [PrimalHQ/primal-caching-service#11]
I'd like to run this with docker-compose

**Comment by ralyodio** [comment]
I've tried this but it just does exit 0.

`docker-compose.yml`:

```
version: '3.8'

services:
  follow-cache:
    image: nixos/nix
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "127.0.0.1:7702:8801"
    environment:
      - PRIMALSERVER_HOST=0.0.0.0
    command: >
      nix --extra-experimental-features 'nix-command flakes' develop -c sh -c '$start_primal_caching_service'
    networks:
      - follows_network
networks:
    follows_network:
      name: follows_network


```

`Dockerfile`

```
# Use the specified base image
FROM nixos/nix

# Set an environment variable
ENV PRIMALSERVER_HOST=0.0.0.0

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Run the specified command when the container launches
CMD ["nix", "--extra-experimental-features", "nix-command flakes", "develop", "-c", "sh", "-c", "$start_primal_caching_service"]

# Expose the port the server is running on
EXPOSE 8801



```


DOes anyone know how to fix?

**Comment by ralyodio** [comment]
Bounty here: 10k sats https://resolvr.io/b/naddr1qprkgmmrddjhycm0d4cx7um994skuepdv3hkx6m9wfnxjmr994jhsctdwpkx2ttxdaez6urjd9kkzmpdvdskx6r994ex2ur094nrzdekv3nxverxvgenzqgdwaehxw309ahx7uewd3hkcq3q9p3l898yf76s73m5pr0ru03a0y8ps6c3se6xcekz8d8v2f676kxsxpqqqp6kygkc83r

**Comment by pritk** [comment]
```
version: '3.8'

services:
  follow-cache:
    image: nixos/nix
    volumes:
      - .:/app
      - ./var/root:/root
    working_dir: /app
    ports:
      - "127.0.0.1:7702:8801"
    environment:
      - PRIMALSERVER_HOST=0.0.0.0
    command: >
      nix --extra-experimental-features 'nix-command flakes' develop -c sh -c '$$start_primal_caching_service'
    stdin_open: true
    tty: true
    networks:
      - follows_network
networks:
    follows_network:
      name: follows_network
```

then you can do, for interactive use:

`docker-compose run follow-cache`

or for non-interactive use:
  
`docker-compose up`
